import { ModeConfig, Persona } from './types';

export const INTERVIEW_MODES: ModeConfig[] = [
  {
    id: 'practice',
    name: 'Practice Mode',
    description: 'Generous hints, low follow-up intensity, unlimited think time. Best for first attempts.',
    hintsAllowed: true,
    interruptFrequency: 'None',
    followUpIntensity: 'Gentle',
    thinkTimeSeconds: 120,
    confidenceLevel: 1,
  },
  {
    id: 'learning',
    name: 'Learning Mode',
    description: 'Structured feedback after each question with real-time guidance on missed key points.',
    hintsAllowed: true,
    interruptFrequency: 'Low',
    followUpIntensity: 'Moderate',
    thinkTimeSeconds: 90,
    confidenceLevel: 2,
  },
  {
    id: 'realistic',
    name: 'Realistic Mode',
    description: 'Standard interview conditions. Realistic pause timers, natural interviewer follow-ups.',
    hintsAllowed: false,
    interruptFrequency: 'Low',
    followUpIntensity: 'Moderate',
    thinkTimeSeconds: 60,
    confidenceLevel: 3,
  },
  {
    id: 'pressure',
    name: 'Pressure Mode',
    description: 'Frequent drill-down follow-ups, strict timer, probes unverified resume claims.',
    hintsAllowed: false,
    interruptFrequency: 'Medium',
    followUpIntensity: 'Rigorous',
    thinkTimeSeconds: 45,
    confidenceLevel: 4,
  },
  {
    id: 'company_sim',
    name: 'Company Simulation',
    description: 'Recreates verified engineering culture, specific domain questions, and interview style.',
    hintsAllowed: false,
    interruptFrequency: 'Medium',
    followUpIntensity: 'Rigorous',
    thinkTimeSeconds: 45,
    confidenceLevel: 4,
  },
  {
    id: 'final_mock',
    name: 'Final Mock',
    description: 'Full-length simulation the night before your real interview. Strict rubric and overall readiness verdict.',
    hintsAllowed: false,
    interruptFrequency: 'High',
    followUpIntensity: 'Relentless',
    thinkTimeSeconds: 30,
    confidenceLevel: 5,
  },
];

export const PERSONAS: Persona[] = [
  {
    id: 'alex-tech-lead',
    name: 'Alex Rivera',
    title: 'Senior Staff Engineer',
    companyStyle: 'Tier-1 Tech Firm',
    avatarUrl: '/avatars/alex.png',
    voiceName: 'en-US-Neural2-F',
    personality: 'Pragmatic, articulate, focuses heavily on system architecture and code clarity.',
    style: 'Direct & constructive',
    tone: 'Calm & professional',
    followUpIntensity: 'moderate',
    interruptionRate: 'low',
    difficulty: 'Level 3',
  },
  {
    id: 'maya-engineering-mgr',
    name: 'Maya Lin',
    title: 'Engineering Director',
    companyStyle: 'High-Growth Startup',
    avatarUrl: '/avatars/maya.png',
    voiceName: 'en-US-Neural2-C',
    personality: 'Warm yet rigorous, probes behavioral STAR stories, leadership, and cross-functional collaboration.',
    style: 'Inquisitive & encouraging',
    tone: 'Conversational',
    followUpIntensity: 'gentle',
    interruptionRate: 'never',
    difficulty: 'Level 2',
  },
  {
    id: 'marcus-strict-interviewer',
    name: 'Marcus Vance',
    title: 'Principal Systems Architect',
    companyStyle: 'Enterprise & Infrastructure',
    avatarUrl: '/avatars/marcus.png',
    voiceName: 'en-US-Neural2-D',
    personality: 'Demanding, tests edge cases, concurrency limitations, and deep computer science fundamentals.',
    style: 'Challenging & analytical',
    tone: 'Formal & sharp',
    followUpIntensity: 'relentless',
    interruptionRate: 'high',
    difficulty: 'Level 5',
  },
  {
    id: 'sarah-product-lead',
    name: 'Sarah Chen',
    title: 'Head of Product Engineering',
    companyStyle: 'Consumer FinTech',
    avatarUrl: '/avatars/sarah.png',
    voiceName: 'en-US-Neural2-H',
    personality: 'Focuses on end-user impact, system tradeoffs, metrics, and technical decision making.',
    style: 'Balanced & thorough',
    tone: 'Encouraging',
    followUpIntensity: 'rigorous',
    interruptionRate: 'medium',
    difficulty: 'Level 4',
  },
];
