import {
  AnswerLibraryItem,
  CoachingSection,
  EvaluationReport,
  InterviewPlan,
  JobAnalysis,
  Persona,
  PracticeAttempt,
  RetryQuestion,
  WeakAreaItem,
} from './shared/types';
import { INTERVIEW_MODES, PERSONAS } from './shared/constants';

export const INITIAL_JOB_ANALYSIS: JobAnalysis = {
  id: 'job-101',
  jobId: 'job-101',
  jobTitle: 'Senior Frontend Engineer',
  company: 'Stripe (Simulated)',
  experienceLevel: 'Mid-Senior (3-5 yrs)',
  jdText: `We are looking for a Senior Frontend Engineer to build robust, scalable payment interfaces using React, TypeScript, and modern web architecture. Requirements: Deep understanding of Browser DOM APIs, web performance, state management, asynchronous data loading, accessibility (WCAG AA), and component design systems. Experience with STAR method behavioral questions and technical system design.`,
  resumeFileName: 'Alex_Chen_Resume_2026.pdf',
  targetInterviewDate: '2026-10-15',
  createdAt: '2026-09-20T10:00:00Z',
  parsedSkills: [
    {
      id: 's1',
      name: 'React & State Architecture',
      category: 'Frontend Core',
      importance: 'primary',
      sourceType: 'verified',
      confidencePct: 88,
      description: 'Extracted directly from JD requirement & candidate project history.',
    },
    {
      id: 's2',
      name: 'TypeScript & Type Systems',
      category: 'Frontend Core',
      importance: 'primary',
      sourceType: 'verified',
      confidencePct: 92,
      description: 'Strict type safety, generics, and API contract design.',
    },
    {
      id: 's3',
      name: 'Web Performance Optimization',
      category: 'Architecture',
      importance: 'primary',
      sourceType: 'verified',
      confidencePct: 74,
      description: 'Core Web Vitals, dynamic imports, bundle size reduction.',
    },
    {
      id: 's4',
      name: 'Accessibility (WCAG AA)',
      category: 'UI/UX Standards',
      importance: 'secondary',
      sourceType: 'inferred',
      confidencePct: 65,
      description: 'Inferred focus based on Stripe checkout accessibility standards.',
    },
    {
      id: 's5',
      name: 'Payment Form Security & PCI',
      category: 'Domain Knowledge',
      importance: 'secondary',
      sourceType: 'reported',
      confidencePct: 58,
      description: 'Reported focus area from public candidate interview reviews.',
    },
    {
      id: 's6',
      name: 'Asynchronous State & Micro-frontends',
      category: 'Architecture',
      importance: 'primary',
      sourceType: 'inferred',
      confidencePct: 70,
      description: 'Inferred requirement for high-concurrency payment streams.',
    },
  ],
  focusAreas: [
    {
      area: 'Component API design & state management tradeoffs',
      rationale: 'Core requirement in JD for reusable design systems.',
      sourceType: 'verified',
    },
    {
      area: 'STAR behavioral response on production outages',
      rationale: 'Standard culture fit requirement for Stripe senior roles.',
      sourceType: 'reported',
    },
    {
      area: 'Web Vitals & micro-performance debugging under pressure',
      rationale: 'Inferred priority given high conversion sensitivity.',
      sourceType: 'inferred',
    },
  ],
};

export const INITIAL_PLAN: InterviewPlan = {
  id: 'plan-101',
  jobId: 'job-101',
  jobTitle: 'Senior Frontend Engineer',
  company: 'Stripe (Simulated)',
  difficulty: 'Level 3 - Realistic Standard',
  mode: 'realistic',
  personaId: 'alex-tech-lead',
  durationMinutes: 45,
  totalQuestions: 6,
  createdAt: '2026-09-20T10:05:00Z',
  rounds: [
    {
      id: 'r1',
      name: 'Warm-up & Background',
      durationMinutes: 5,
      questionCount: 1,
      topics: ['Self-Introduction', 'Career summary'],
    },
    {
      id: 'r2',
      name: 'Behavioral & STAR',
      durationMinutes: 10,
      questionCount: 1,
      topics: ['Handling technical debt', 'Cross-team communication'],
    },
    {
      id: 'r3',
      name: 'Technical Depth',
      durationMinutes: 15,
      questionCount: 2,
      topics: ['React rendering lifecycle', 'Web performance profiling'],
    },
    {
      id: 'r4',
      name: 'Live Coding Lab',
      durationMinutes: 10,
      questionCount: 1,
      topics: ['Custom Hook / Debounced Search component implementation'],
    },
    {
      id: 'r5',
      name: 'Candidate Questions & Closing',
      durationMinutes: 5,
      questionCount: 1,
      topics: ['Team engineering practices', 'Closing thoughts'],
    },
  ],
};

export const RECENT_EVALUATION_REPORT: EvaluationReport = {
  sessionId: 'sess-892',
  overallScore: 78,
  verdict: 'Almost there',
  summaryLine: 'Strong technical accuracy on React lifecycle; self-introduction and STAR behavioral structure need tighter focus.',
  generatedAt: '2026-09-22T14:30:00Z',
  categories: [
    { name: 'technical', label: 'Technical correctness', score: 84, weight: 30, summary: 'Accurate explanation of virtual DOM diffing and memoization.' },
    { name: 'communication', label: 'Communication & structure', score: 68, weight: 20, summary: 'Lacks STAR structure in behavioral answers; rambles slightly during self-intro.' },
    { name: 'coding', label: 'Coding round', score: 85, weight: 15, summary: 'Clean implementation of debounced search with unit checks passed.' },
    { name: 'speech', label: 'Speech delivery', score: 72, weight: 15, summary: 'Average pace of 135 WPM, 8 filler words ("um", "like") detected.' },
    { name: 'confidence', label: 'Confidence', score: 75, weight: 10, summary: 'Minor hedging ("I think maybe...") when asked about browser memory leaks.' },
    { name: 'body_language', label: 'Body language & presence', score: 88, weight: 5, summary: 'Face visible 96% of time, steady eye-contact alignment.' },
    { name: 'professionalism', label: 'Professionalism', score: 90, weight: 5, summary: 'Clear mic setup, punctual, responsive.' },
  ],
  metrics: {
    wordsPerMinute: 135,
    fillerCount: 8,
    fillerPerMinute: 2.1,
    hedgeCount: 4,
    avgPauseMs: 650,
    faceVisiblePct: 96,
    eyeContactPct: 84,
  },
  questions: [
    {
      questionId: 'q1',
      questionText: 'Tell me about yourself and why you are interested in this Senior Frontend Engineer role at Stripe.',
      candidateAnswer: 'Uh, hi! So I have been doing frontend for around 4 years now. Mostly React and TypeScript. In my last job, we built a lot of dashboards and stuff. I really like Stripe because payments are interesting and I think I can bring good skills to the team.',
      round: 'Warm-up',
      score: 64,
      dimensions: {
        relevance: 70,
        technicalAccuracy: 75,
        structure: 55,
        specificity: 50,
        confidence: 60,
      },
      strengths: ['Mentions relevant stack (React & TypeScript).', 'Expresses clear interest in Stripe payment domain.'],
      improvements: [
        'Lacks a crisp 60-second elevator pitch structure (Past -> Present -> Future impact).',
        'Vague descriptions ("dashboards and stuff") weaken impact.',
        'Opening filler ("Uh, hi! So...") reduces initial gravitas.',
      ],
      suggestedStructure: [
        'Highlight core engineering identity and total years of focused frontend experience.',
        'Cite 1 high-impact quantifiable metric from recent role.',
        'Connect your specific mastery in performance/reliability directly to Stripe payment interfaces.',
      ],
      evidence: [{ quote: 'built a lot of dashboards and stuff', atMs: 12400 }],
      idealAnswer: 'I am a Frontend Engineer with over 4 years of experience specializing in high-scale React and TypeScript web applications. At my previous role, I led the frontend architecture for our core checkout portal, optimizing bundle sizes by 32% and serving over 200,000 daily users. I have followed Stripe’s developer-first philosophy for years, and I am excited to bring my focus on web performance and component accessibility to your payment engineering team.',
    },
    {
      questionId: 'q2',
      questionText: 'Describe a time when you had to resolve a complex production outage under pressure.',
      candidateAnswer: 'Yeah, so one time our checkout API started timing out during a flash sale. I looked at devtools and realized we were triggering re-renders continuously because of an un-memoized context value. I pushed a hotfix with useMemo and fixed it in about 20 minutes.',
      round: 'Behavioral & STAR',
      score: 74,
      dimensions: {
        relevance: 85,
        technicalAccuracy: 80,
        structure: 65,
        specificity: 70,
        confidence: 70,
      },
      strengths: ['Identified root cause quickly (context re-render).', 'Concrete technical resolution with useMemo.'],
      improvements: [
        'Skipped the Situation & Task context (business impact, scale).',
        'Needs clear quantified result (e.g., latency dropped from 4s to 120ms).',
      ],
      suggestedStructure: [
        'S: Describe the scale of the outage and user impact.',
        'T: Explain your specific ownership role.',
        'A: Detail step-by-step diagnostic and hotfix actions.',
        'R: Share measurable recovery metrics.',
      ],
      evidence: [{ quote: 'fixed it in about 20 minutes', atMs: 45000 }],
      idealAnswer: 'During a Black Friday flash sale, our primary checkout portal experienced latency spikes up to 5 seconds. As lead on-call frontend engineer, my immediate task was to isolate the client-side regression without taking down the payment gateway. By running performance profiles in Chrome DevTools, I discovered an unmemoized global Context provider triggering thousands of unnecessary DOM re-renders per second. I implemented a targeted useMemo cache and deployed a hotfix within 15 minutes, restoring checkout response times to under 150ms and preventing an estimated $40k in dropped transactions.',
    },
    {
      questionId: 'q3',
      questionText: 'How does React’s reconciliation algorithm handle key props in dynamic lists?',
      candidateAnswer: 'Keys give React a stable identity for array elements across renders. Without keys or using index as key, React might mutate state incorrectly when items are reordered, because it relies on array indices instead of identity tracking.',
      round: 'Technical Depth',
      score: 91,
      dimensions: {
        relevance: 95,
        technicalAccuracy: 95,
        structure: 90,
        specificity: 85,
        confidence: 90,
      },
      strengths: ['Precise technical explanation of fiber node reconciliation.', 'Correctly highlighted risks of using index as key.'],
      improvements: ['Could briefly mention heuristic O(N) complexity vs O(N^3) matrix diffing.'],
      suggestedStructure: [
        'Define key role in fiber diffing algorithm.',
        'Contrast stable IDs vs array indices.',
        'Mention O(N) time complexity assumption.',
      ],
      evidence: [{ quote: 'relies on array indices instead of identity tracking', atMs: 82000 }],
      idealAnswer: 'React’s reconciliation algorithm uses key props to achieve an O(N) heuristic diffing algorithm rather than an O(N^3) tree comparison. When rendering lists, key props provide a persistent identifier across render trees. If items are re-ordered or filtered, React matches Fiber nodes by key, preserving local state and avoiding expensive DOM teardowns. Using index as a key breaks this heuristic because shifting indices forces React to re-use incorrect component instances and corrupt internal hook state.',
    },
  ],
  timeline: [
    { atMs: 5000, type: 'mic_low', note: 'Mic input lower than recommended during warm-up.' },
    { atMs: 12400, type: 'filler_spike', note: '3 filler words ("uh", "like") in 10 seconds.' },
    { atMs: 45000, type: 'barge_in', note: 'Candidate interrupted interviewer brief politely.' },
    { atMs: 82000, type: 'code_submit', note: 'Coding exercise submitted with 4/4 test cases passing.' },
  ],
  topRecommendations: [
    'Use the 3-part Elevator Pitch framework for your Self-Introduction (Identity -> Quantified Impact -> Role Alignment).',
    'Structure behavioral answers strictly with STAR (Situation, Task, Action, Result).',
    'Eliminate hedging phrases ("I think maybe") when discussing web performance profiling.',
  ],
};

export const INITIAL_COACHING_SECTIONS: CoachingSection[] = [
  {
    id: 'coach-sec-1',
    sessionId: 'sess-892',
    questionId: 'q1',
    sectionType: 'intro',
    questionText: 'Tell me about yourself and why you are interested in this Senior Frontend Engineer role at Stripe.',
    originalText: 'Uh, hi! So I have been doing frontend for around 4 years now. Mostly React and TypeScript. In my last job, we built a lot of dashboards and stuff. I really like Stripe because payments are interesting and I think I can bring good skills to the team.',
    issues: [
      'Weak opening without clear engineering identity or title.',
      'Unstructured narrative lacking measurable achievements ("built dashboards and stuff").',
      'Generic closing statement rather than role-specific value proposition.',
    ],
    rewrittenText: 'I am a Frontend Engineer with 4 years of experience specializing in high-concurrency React and TypeScript web applications. At my previous company, I architected our core checkout workflow, optimizing Web Vitals and reducing bundle load time by 32% for 200,000 daily active users. I have followed Stripe’s developer tooling standards closely, and I am excited to apply my focus on web performance and component architecture to your payment engineering team.',
    reasoning: [
      'Establishes immediate authority with a clean professional identity.',
      'Quantifies impact (32% bundle load reduction, 200,000 users) based strictly on candidate-provided domain context.',
      'Aligns technical expertise directly with Stripe’s core focus.',
    ],
    tipIds: ['tip-intro-1', 'tip-intro-2'],
    practiced: false,
    createdAt: '2026-09-22T14:35:00Z',
  },
  {
    id: 'coach-sec-2',
    sessionId: 'sess-892',
    questionId: 'q2',
    sectionType: 'behavioral',
    questionText: 'Describe a time when you had to resolve a complex production outage under pressure.',
    originalText: 'Yeah, so one time our checkout API started timing out during a flash sale. I looked at devtools and realized we were triggering re-renders continuously because of an un-memoized context value. I pushed a hotfix with useMemo and fixed it in about 20 minutes.',
    issues: [
      'Missing STAR Situation setup (scale, revenue at risk, latency numbers).',
      'Jumped straight to diagnosis without explaining your ownership responsibilities.',
      'Lacks quantifiable business recovery outcome.',
    ],
    rewrittenText: 'During a high-traffic flash sale, our primary payment page experienced latency spikes reaching 5 seconds. As lead frontend engineer on-call, my goal was to diagnose the root cause without taking down live checkout streams. By running performance traces in Chrome DevTools, I discovered an unmemoized Context provider triggering thousands of unnecessary DOM re-renders per minute. I deployed a targeted memoization fix within 15 minutes, restoring latency to under 150ms and preventing dropped transactions.',
    reasoning: [
      'Uses strict STAR structure with clear Situation metrics (5s latency spike).',
      'Highlights proactive ownership and methodical debugging under time pressure.',
      'Ends with clear recovery metric (under 150ms response time).',
    ],
    tipIds: ['tip-star-1'],
    practiced: true,
    createdAt: '2026-09-22T14:35:00Z',
  },
];

export const INITIAL_PRACTICE_ATTEMPTS: PracticeAttempt[] = [
  {
    id: 'prac-1',
    coachingSectionId: 'coach-sec-2',
    attemptText: 'During a flash sale, our payment page spiked to 5s latency. As on-call frontend lead, I profiled the app in DevTools, found an unmemoized Context provider causing thousands of re-renders, and pushed a useMemo hotfix in 15 minutes, bringing latency back under 150ms.',
    score: 88,
    comparedToOriginalDelta: 14,
    createdAt: '2026-09-22T16:00:00Z',
  },
];

export const WEAK_AREAS_DATA: WeakAreaItem[] = [
  {
    id: 'wa-1',
    category: 'Communication Structure',
    title: 'Behavioral Answer STAR Structure',
    frequencyCount: 4,
    lastOccurredDate: '2026-09-22',
    impactScore: 8.5,
    recommendation: 'Always open with Situation scale (users, latency, revenue) before jumping into technical debugging steps.',
  },
  {
    id: 'wa-2',
    category: 'Speech Delivery',
    title: 'Opening Filler Words ("Uh", "So", "Like")',
    frequencyCount: 6,
    lastOccurredDate: '2026-09-22',
    impactScore: 7.2,
    recommendation: 'Pause for 1 second after interviewer finishes speaking instead of filling the pause with "Uh" or "So".',
  },
  {
    id: 'wa-3',
    category: 'Technical Specificity',
    title: 'Hedging Language in Architecture Questions',
    frequencyCount: 3,
    lastOccurredDate: '2026-09-21',
    impactScore: 6.8,
    recommendation: 'Replace "I think maybe..." with "In my experience, the optimal tradeoff is..."',
  },
];

export const RETRY_MISTAKES_DATA: RetryQuestion[] = [
  {
    id: 'retry-1',
    questionText: 'Tell me about yourself and why you are interested in this Senior Frontend Engineer role.',
    jobTitle: 'Senior Frontend Engineer @ Stripe',
    previousScore: 64,
    round: 'Warm-up',
    dateAsked: '2026-09-22',
  },
  {
    id: 'retry-2',
    questionText: 'Describe a time when you had to resolve a complex production outage under pressure.',
    jobTitle: 'Senior Frontend Engineer @ Stripe',
    previousScore: 74,
    round: 'Behavioral',
    dateAsked: '2026-09-22',
  },
  {
    id: 'retry-3',
    questionText: 'How would you optimize a React app suffering from high layout thrashing?',
    jobTitle: 'Frontend Lead @ Vercel',
    previousScore: 68,
    round: 'Technical',
    dateAsked: '2026-09-18',
  },
];

export const ANSWER_LIBRARY_DATA: AnswerLibraryItem[] = [
  {
    id: 'ans-1',
    questionText: 'Tell me about yourself and why you are interested in this Senior Frontend Engineer role at Stripe.',
    category: 'Self-Introduction',
    answerText: 'I am a Frontend Engineer with 4 years of experience specializing in high-concurrency React and TypeScript web applications...',
    score: 88,
    jobTitle: 'Senior Frontend Engineer',
    date: '2026-09-22',
    tags: ['Self Intro', 'Stripe', 'React'],
  },
  {
    id: 'ans-2',
    questionText: 'How does React’s reconciliation algorithm handle key props in dynamic lists?',
    category: 'Technical',
    answerText: 'React’s reconciliation algorithm uses key props to achieve an O(N) heuristic diffing algorithm rather than an O(N^3) tree comparison...',
    score: 91,
    jobTitle: 'Senior Frontend Engineer',
    date: '2026-09-22',
    tags: ['React', 'Diffing', 'Fiber'],
  },
  {
    id: 'ans-3',
    questionText: 'Describe a time when you resolved a production outage under pressure.',
    category: 'Behavioral',
    answerText: 'During a high-traffic flash sale, our payment page experienced latency spikes reaching 5 seconds. As lead frontend engineer on-call...',
    score: 88,
    jobTitle: 'Senior Frontend Engineer',
    date: '2026-09-22',
    tags: ['STAR', 'Outage', 'Performance'],
  },
];
